name: Onboarding Request
description: Request that a software tool be onboarded to the NOAA Fisheries Integrated Toolbox (FIT).
title: "Onboarding Request: [tool name] "
labels: ["Onboarding Request"]
assignees:
  - k-doering-NOAA
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a tool onboarding request to the NOAA Fisheries Integrated Toolbox (FIT)! To learn more about the FIT and the software it contains, see [the FIT's About Page](https://noaa-fisheries-integrated-toolbox.github.io/resources/about/). To add links within text, please use html a tag syntax with escaped quotations (e.g., `<a href=\"https://noaa-fisheries-integrated-toolbox.github.io/\">FIT</a>`) rather than using markdown syntax. Plain URLs are also acceptable. 
  - type: dropdown
    id: activedev
    attributes:
      label: Active Development
      description: Is the code or tool in active development? (If inactive, please consider whether a replacement tool in active development would be more appropriate to onboard to the toolbox).
      options:
        - "Yes"
        - "No"
    validations:
      required: true
    # Links to the Tool
  - type: markdown
    attributes:
      value: |
        ## Basic Tool Metadata
  - type: input
    id: toolname
    attributes:
      label: Tool name
      placeholder: Stock Synthesis
    validations:
      required: true
  - type: input
    id: toolabbreviation
    attributes:
      label: Tool abbreviation
      placeholder: SS3
    validations:
      required: true
  - type: input
    id: authors
    attributes:
      label: Author(s)
      description: Please include tool author names in the format provided. Tool authors include those who has made significant contributions to the tool.
      placeholder: Maria Rodriguez, David Nguyen, Aliza Scott
    validations:
      required: true
  - type: input
    id: contributors
    attributes:
      label: Contributor(s)
      description: Please include contributor names in the format provided. Contributors include those who have made small contributions to the tool.
      placeholder: Jane Smith, John Robinson
    validations:
      required: false
  - type: input
    id: logo
    attributes:
      label: Tool logo
      description: If desired, provide a link to a .png or .jpg file that will be shown on the tool webpage.
      placeholder: https://github.com/nmfs-fish-tools/SSMSE/blob/main/man/figures/ssmse_icon_small.png?raw=true
    validations:
      required: false
  - type: dropdown
    id: noaainternal
    attributes:
      label: NOAA Internal
      description: Is this tool maintained by NOAA employees or affiliates?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: maintainername
    attributes:
      label: Maintainer Name
      description: Please include the primary maintainer's name in the format provided.
      placeholder: Maria Rodriguez
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Maintainer Email
      description: Email address of primary maintainer for this tool.
      placeholder: fisheries.toolbox@noaa.gov
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Background Text
      description: One paragraph general description of the tool for users. This will be the main text on the model landing page.
      placeholder: The Age Structured Assessment Program (ASAP) is an age-structured model that uses forward computations assuming separability of fishing mortality into year and age components to estimate population sizes given observed catches, catch-at-age, and indices of abundance. Discards can be treated explicitly. The separability assumption is relaxed by allowing for fleet-specific computations and by allowing the selectivity at age to change smoothly over time or in blocks of years. The software can also allow the catchability associated with each abundance index to vary smoothly with time. The problem’s dimensions (number of ages, years, fleets and abundance indices) are defined at input and limited by hardware only. The input is arranged assuming data is available for most years, but missing years are allowed. The model currently does not allow use of length data nor indices of survival rates. Diagnostics include index fits, residuals in catch and catch-at-age, and effective sample size calculations. Weights are input for different components of the objective function and allow for relatively simple age-structured production model type models up to fully parameterized models. The calculation engine was built using AD Model Builder by Drs. Christopher M. Legault (currently at the NMFS Northeast Fisheries Science Center) and Victor R. Restrepo (currently at the NMFS Southeast Fisheries Science Center). ASAP has been used as an assessment tool for red grouper (SEFSC), yellowtail flounder (NEFSC), Pacific sardine (SWFSC), Pacific mackerel (SWFSC), Greenland halibut (ICES), Norther Gulf of St. Lawrence cod (DFO), Gulf of Maine cod (NEFSC), Florida lobster (FFWCC), and fluke (NEFSC).
    validations:
      required: true
  - type: input
    id: citelink
    attributes:
      label: Citation
      description: Let users know how to cite the tool. Preferably, a link to the DOI for an article. Other options include using [Zenodo](https://zenodo.org/) to generate a DOI for the source code. If including a text string, please format it using [APA style](https://apastyle.apa.org/style-grammar-guidelines/references/examples).
      placeholder: https://doi.org/10.1016/j.fishres.2012.10.012
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References
      description: Link to references (journal articles or other documentation) related to the tool, preferably the link to the DOI, if available. If there are multiple references, please put one per line (press enter between references). This should NOT be the same as the citation.
      placeholder: "https://doi.org/10.1016/j.fishres.2012.10.012"
    validations:
      required: false
  - type: textarea
    id: associatedtools
    attributes:
      label: Associated Tools
      description: Provide names and links of any associated tools in format of example shown below.
      placeholder: r4ss https://r4ss.github.io/r4ss/, ss3sim https://ss3sim.github.io/ss3sim/
    validations:
      required: false
  - type: input
    id: userorganizations
    attributes:
      label: User Organizations
      description: List all science organizations that use this tool operationally (e.g., NOAA science centers, Regional Fishery Management Organizations)
      placeholder: NOAA Northwest Fisheries Science Center, NOAA Southeast Fisheries Science Center, NOAA Southwest Fisheries Science Center
    validations:
      required: false
  # Links to the Tool
  - type: markdown
    attributes:
      value: |
        ## Links To the Tool
        Please provide as many as applicable. At least 1 link is required in order to onboard to FIT.
  - type: input
    id: onlineapplink
    attributes:
      label: Online App Link
      description: Link to the Online App. Note, if you would like to host your app on the NMFS Posit Connect Server, please note that in the comments area of the form and we will get you set up before onboarding the tool.
      placeholder: https://connect.fisheries.noaa.gov/DLMapper/
    validations:
      required: false
  - type: input
    id: exelink
    attributes:
      label: Executable Link
      description: Link the compiled version of the tool, if available.
      placeholder: https://github.com/nmfs-fish-tools/SSMSE/releases
    validations:
      required: false
  - type: input
    id: websitelink
    attributes:
      label: Website Link
      description: Link to the tool's website, if available.
      placeholder: https://vlab.noaa.gov/web/stock-synthesis
    validations:
      required: false            
  - type: input
    id: documentationlink
    attributes:
      label: Documentation Link
      placeholder: https://nmfs-fish-tools.github.io/SSMSE/manual/
    validations:
      required: false
  - type: input
    id: sourcecodelink
    attributes:
      label: Source Code Link
      placeholder: https://github.com/nmfs-fish-tools/SSMSE
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Detailed Tool Metadata
  - type: textarea
    id: badges
    attributes:
      label: Software Badges
      description:  Badges are used to indicate important information about software to users. Add as few as 0 and up to 3 URLs for software badges that you would like displayed. Separate the plain URLS with commas (no markdown or html a tag syntax, please). Badges typically come from [shields.io](https://shields.io/), [repostatus.org](https://www.repostatus.org/), or [GitHub actions](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge).
      placeholder: https://www.repostatus.org/badges/latest/active.svg, https://img.shields.io/badge/platform-linux%20%7Cwin-lightgrey
    validations:
      required: false
  - type: textarea
    id: installation
    attributes:
      label: Installation instructions
      description: Short instructions on how to use the tool. Please include [html formatting](https://www.simplehtmlguide.com/cheatsheet.php) instead of markdown.
      placeholder: "In R, install from GitHub:<br><br><code>remotes::install_github(\"nmfs-fish-tools/SSMSE\")</code><br><br>More details on installation are available on <a href=\"https://github.com/nmfs-fish-tools/ssmse?tab=readme-ov-file#installing-the-ssmse-r-package\">the SSMSE readme</a>."
    validations:
      required: false
  - type: checkboxes
    id: drawer
    attributes:
      label: Toolbox Drawers
      description: Which drawer(s) of the toolbox does this tool belong in? Check any that apply.
      options:
        - label: Ecosystems
        - label: Fish and Fisheries
        - label: Human Dimensions
        - label: Protected Species
        - label: General Modeling Tools
        - label: Utility Tools
  - type: checkboxes
    id: keywords
    attributes:
      label: Keywords
      description: Check up to 5 keywords that describe the tool. Have additional keyword suggestions? Include in the questions and comments section.
      options:
        - label: "ADMB"
        - label: "Age Structured Model"
        - label: "Bayesian Modeling"
        - label: "Bycatch"
        - label: "C++"
        - label: "Calculator"
        - label: "Data Exploration"
        - label: "Data Limited Method"
        - label: "Data Visualization"
        - label: "Decision Support Tool"
        - label: "Developer Utilities"
        - label: "Economics"
        - label: "Ecosystem"
        - label: "Ensemble Modeling"
        - label: "Fish Biology"
        - label: "Fisheries"
        - label: "Gradient Solver"
        - label: "Guided User Interface"
        - label: "Individual Based Model"
        - label: "Legacy Tool"
        - label: "Length Structured Model"
        - label: "Management Strategy Evaluation"
        - label: "Marine Mammals"
        - label: "Maximum Likelihood Estimation"
        - label: "Model Builder"
        - label: "Model Comparision"
        - label: "Multispecies Model"
        - label: "Natural Mortality Model"
        - label: "NOAA Branding"
        - label: "North Pacific"
        - label: "Output Visualization"
        - label: "Projection Modeling"
        - label: "R Package"
        - label: "Reference Points Model"
        - label: "Risk Assessment Tool"
        - label: "Salmon"
        - label: "Sampling Decision Tool"
        - label: "Shiny"
        - label: "Simulation"
        - label: "Size Spectra Model"
        - label: "Size Structured Model"
        - label: "Socioeconomics"
        - label: "Spatial Model"
        - label: "Species Distribution Model"
        - label: "Standardized Reporting"
        - label: "Stock Assessment Model"
        - label: "Stock Assessment Projections"
        - label: "Stock Assessment Tool"
        - label: "Surplus Production Model"
        - label: "Tag Data Model"
        - label: "Teaching Tool"
        - label: "Time Series"
        - label: "TMB"
        - label: "User Utilities"
        - label: "Virtual Population Analysis"
        - label: "Visualization"
        - label: "Web App"
  - type: dropdown
    id: releases
    attributes:
      label: Uses Github Releases
      description: Does the codebase use releases on GitHub? Must include Source Code Link above if answering yes. (If not, we HIGHLY recommend considering using releases to keep the version number on the toolbox up to date)
      options: 
        - "Yes"
        - "No"
        - "I plan to use them in the near future"
    validations:
      required: true
  - type: input
    id: versionnumber
    attributes:
      label: Static version number
      description: If not using GitHub releases and the version number is not likely to change, please add the latest version number. Please don't provide a version number if it will change frequently, as we don't have a good way to make sure it stays up to date if not using GitHub releases.
      placeholder: 0.9.0
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Please add any additional questions or comments
      placeholder:
    validations:
      required: false
  # - type: checkboxes
  #   id: langs
  #   attributes:
  #     label: which language(s) is the tool written in? (note: could pull this from github meta data)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)
          required: true
